/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package helpinghands;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.awt.Color;
/**
 *
 * @author hi
 */
public class Foodtypes extends javax.swing.JFrame {

    /**
     * Creates new form Foodtypes
     */
    public Foodtypes() {
        initComponents();
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);
        jTextArea1.setBorder(null);
        jTextArea1.setBackground(new Color(0,0,0,64));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        getContentPane().setLayout(null);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(613, 34, 108, 34);

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Food Types");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 180, 80, 16);

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No of persons");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 220, 102, 16);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(600, 210, 74, 30);

        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jButton1.setText("PROCEED");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(450, 340, 93, 25);

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Area");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 260, 67, 16);

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EMPLOYEE NAME");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 300, 111, 16);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(600, 290, 170, 30);

        jComboBox1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chappathi", "Meals", "Noodles", "Coffee", "Tiffin" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(600, 180, 89, 20);

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("THE CHARITY HOMES AVAILABLE NEAR THE AREA YOU HAVE SPECIED :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 380, 652, 16);

        jButton2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jButton2.setText("CONFIRM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(540, 570, 95, 25);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(420, 410, 560, 107);

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("THE CHARITY HOME NAME YOU WANT TO DONATE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 540, 356, 16);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(770, 530, 226, 30);

        jButton3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton3.setText(">>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(760, 570, 55, 27);

        jLabel11.setIcon(new javax.swing.ImageIcon("E:\\apsara\\f2.jpg")); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(350, 100, 660, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon("E:\\apsara\\f2.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(350, 600, 660, 60);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "peelamedu", "saibaba colony", "gandhipuram", "singanallur", "race course", "rs puram" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(600, 260, 100, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\apsara\\gbg (1).jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(350, 150, 660, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String ename,rname,ph;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String s1 = (String) jComboBox1.getSelectedItem();
        int s2=Integer.parseInt(jTextField1.getText());
        String s3=(String) jComboBox2.getSelectedItem();
        String s4=jTextField3.getText();
         try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Kavitha_005");
            Statement smt=con.createStatement();
           
            ResultSet rs=smt.executeQuery("insert into foodtypes values('"+s1+"',"+s2+",'"+s3+"')");
            ResultSet rs1=smt.executeQuery("select charity_name from charity where charity_area='"+s3+"'");
            //ResultSet rs1=smt.executeQuery("select charity_name from charity");
            int check=0;
            while(rs1.next())
            {
                String cname=rs1.getString("charity_name");
                jTextArea1.append(" \n ");
                jTextArea1.append(cname);
                check=1;
                //System.out.format("%s\n",cname);
            }
            if(check==0)
            {
                String msg1="sorry no charity homes near your area..!Enter another area which would be comfortable for you to deliver";
                JOptionPane.showMessageDialog(null,msg1);
            }
            //String s5=jTextField5.getText();
            
            con.close();
        }catch(Exception e){System.out.println(e);} 
         //this.dispose();
         
        //resthanku second=new resthanku();
        //second.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    String cname;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String s1 = (String) jComboBox1.getSelectedItem();
        int s2=Integer.parseInt(jTextField1.getText());
        String s3=(String) jComboBox2.getSelectedItem();
        String s4=jTextField3.getText();
        String s5=jTextField5.getText();
         try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Kavitha_005");
            Statement smt=con.createStatement();
         
            //ResultSet rs1=smt.executeQuery("select charity_name from charity where charity_area='"+s3+"'");
            ResultSet rs4=smt.executeQuery("select charity_name from charity where charity_name='"+s5+"'");
            
            //ResultSet rs2=smt.executeQuery("select res_name,emp_name from employee where emp_id='"+s4+"'");
            //ResultSet rs3=smt.executeQuery("select charity_name from charity where charity_name='"+s5+"'");
            while(rs4.next())
            {
              cname=rs4.getString("charity_name");
                
            }
             ResultSet rs2=smt.executeQuery("select res_name,emp_name,emp_phone from employee where emp_name='"+s4+"'");
            while(rs2.next())
            {
                rname=rs2.getString("res_name");
                ename=rs2.getString("emp_name");
                ph=rs2.getString("emp_phone");
            }
            String msg=ename + "(" + ph +") will deliver the food from  " + rname + " to  " +cname;
            JOptionPane.showMessageDialog(null,msg);
           ResultSet rs5=smt.executeQuery("insert into record_f values('"+rname+"','"+ename+"','"+cname+"')");
            con.close();
        }catch(Exception e){System.out.println(e);}   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
    this.dispose();
    resthanku v=new resthanku();
    v.setVisible(true);
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Foodtypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Foodtypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Foodtypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Foodtypes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Foodtypes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
