/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package helpinghands;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author hi
 */
public class restaurant_new extends javax.swing.JFrame {

    /** Creates new form restaurant_new */
    public restaurant_new() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(630, 150, 190, 30);

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Restaurant Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(450, 160, 160, 16);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(630, 200, 190, 30);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("e-mail id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(450, 210, 130, 16);

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Area");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 250, 80, 16);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(630, 280, 190, 30);

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Contact");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(450, 290, 100, 16);

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Employee Details:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 320, 160, 16);

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 0));
        jLabel5.setText("Employee1");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(450, 350, 100, 16);

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(470, 380, 50, 16);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(530, 370, 116, 30);

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Contact");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(680, 380, 70, 16);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(760, 370, 116, 30);

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 0));
        jLabel10.setText("Employee2");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(450, 420, 90, 16);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(530, 450, 116, 30);

        jLabel11.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Name");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(470, 460, 50, 16);

        jLabel13.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Contact");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(690, 460, 70, 16);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(770, 450, 116, 30);

        jLabel14.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 0));
        jLabel14.setText("Employee3");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(450, 490, 80, 16);

        jLabel15.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Name");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(470, 520, 40, 16);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(530, 510, 116, 30);

        jLabel17.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Contact");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(690, 520, 70, 16);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(770, 510, 116, 30);

        jButton1.setBackground(new java.awt.Color(51, 51, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGISTER & DONATE NOW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(440, 590, 220, 25);

        jButton2.setBackground(new java.awt.Color(51, 51, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REGISTER NOW AND DONATE LATER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(530, 630, 281, 25);

        jButton3.setBackground(new java.awt.Color(51, 51, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(700, 590, 163, 23);

        jLabel18.setFont(new java.awt.Font("Imprint MT Shadow", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 0));
        jLabel18.setText("FORM");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(640, 100, 110, 23);

        jComboBox1.setMaximumRowCount(10);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "peelamedu", "saibaba colony", "gandhipuram", "singanallur", "race course", "rs puram" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(630, 250, 100, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\apsara\\gbg (1).jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(410, 80, 520, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String s1=jTextField1.getText();
        String s2=jTextField2.getText();
        String s3=(String) jComboBox1.getSelectedItem();
        String s4=jTextField4.getText();
        String y="yes";
        String s5=jTextField5.getText();//1st name
        String s6=jTextField8.getText();//2nd name
        String s7=jTextField11.getText();//3rd name
        String s11=jTextField7.getText();//1st con
        String s12=jTextField10.getText();//2nd con
        String s13=jTextField13.getText();//3rd con
        if(s4.length()==10 && s11.length()==10 && s12.length()==10 && s13.length()==10)
        {
            try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Kavitha_005");
            Statement smt=con.createStatement();
           
            ResultSet rs=smt.executeQuery("insert into restaurant values('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+y+"')");
            ResultSet rs1=smt.executeQuery("insert into employee values('"+s1+"','"+s5+"','"+s11+"')");
            ResultSet rs2=smt.executeQuery("insert into employee values('"+s1+"','"+s6+"','"+s12+"')");
            ResultSet rs3=smt.executeQuery("insert into employee values('"+s1+"','"+s7+"','"+s13+"')");
            con.close();
        }catch(Exception e){System.out.println(e);} 
       this.dispose();
        Foodtypes sec=new Foodtypes();
        sec.setVisible(true);
        }
        else
        {
            String msg="Please enter a valid phone number";
            JOptionPane.showMessageDialog(null,msg);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String s1=jTextField1.getText();
        String s2=jTextField2.getText();
        String s3=(String) jComboBox1.getSelectedItem();
        String s4=jTextField4.getText();
        String y="yes";
        String s5=jTextField5.getText();//1st name
        String s6=jTextField8.getText();//2nd name
        String s7=jTextField11.getText();//3rd name

        String s11=jTextField7.getText();//1st con
        String s12=jTextField10.getText();//2nd con
        String s13=jTextField13.getText();//3rd con
        if(s4.length()==10 && s11.length()==10 && s12.length()==10 && s13.length()==10)
        {
           try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","Kavitha_005");
            Statement smt=con.createStatement();
           
            ResultSet rs=smt.executeQuery("insert into restaurant values('"+s1+"','"+s2+"','"+s3+"','"+s4+"','"+y+"')");
            ResultSet rs1=smt.executeQuery("insert into employee values('"+s1+"','"+s5+"','"+s11+"')");
            ResultSet rs2=smt.executeQuery("insert into employee values('"+s1+"','"+s6+"','"+s12+"')");
            ResultSet rs3=smt.executeQuery("insert into employee values('"+s1+"','"+s7+"','"+s13+"')");
            con.close();
        }catch(Exception e){System.out.println(e);} 
       dbms1 sec=new dbms1();
       sec.setVisible(true);
        }
        else
        {
            String msg="Please enter a valid phone number";
            JOptionPane.showMessageDialog(null,msg);
        }
             // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            dbms1 sec=new dbms1();
            sec.setVisible(true);
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(restaurant_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(restaurant_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(restaurant_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(restaurant_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new restaurant_new().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

}
